name: Build Python Package with PyInstaller

on:
  push:
    branches:
      - main  # Запускать сборку при пуше в ветку main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name=minimizeglazewm main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minimizeFocusedWorkspaceGalzeWM-Windows
          path: dist/

      - name: Create Tag
        id: create_tag
        shell: pwsh  # Используем PowerShell
        run: |
          $TAG_NAME = "v1.0.${{ github.run_number }}"
          echo "TAG_NAME=$TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}  # Используем созданный тег
          files: |
            dist/minimizeglazewm.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}