name: Build Python Package with PyInstaller

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name=minimizeglazewm main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minimizeFocusedWorkspaceGalzeWM-Windows
          path: dist/

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: minimizeFocusedWorkspaceGalzeWM-Windows
          path: dist/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/minimizeglazewm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
