name: Build Python Package with PyInstaller

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name=minimizeglazewm main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: minimizeFocusedWorkspaceGalzeWM-Windows
          path: dist/